### ISSUE TITLE
Accept base.ts file path as parameter

### ISSUE THREAD

**Issue by lgmferrari** [kopz9999/ng-node-environment#1]
I have an Angular app that has multiple projects. All of them are using the same environment config, and also they all lay in `projects` folder. It would be nice to have the `base.ts` inside that folder too. 

The idea is to specify the target file destination using a parameter. 
```
node ng-node-environment --path "projects"
```
This action would create a `projects/environments/base.ts` file with my `.env` content.

**Comment by kopz9999** [comment]
@lgmferrari added this option on latest release
https://github.com/kopz9999/ng-node-environment#multiple-environments-with-json
