### ISSUE TITLE
Replace double-quotemark by quotemark

### ISSUE THREAD

**Issue by Ferrzo** [kopz9999/ng-node-environment#2]
Could you replace quotemarks in base.ts result file? Because linter is raising an error.

**Comment by kopz9999** [comment]
@Ferrzo sure thing

**Comment by kopz9999** [comment]
@Ferrzo merged and published on npm with your changes, thanks bud!

**Comment by kopz9999** [comment]
@all-contributors please add @Ferrzo  for Replace double-quotemark by quotemark

**Comment by kopz9999** [comment]
@all-contributors please add @Ferrzo for code
